version: "3.12"

services:
  backend:
    build: .
    container_name: backend2
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./core:/app
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - EMAIL_HOST=smtp
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False
    depends_on:
      - smtp
      - redis

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A core worker -l info
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A core beat -l info
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_todo
    ports:
      - "6380:6379"

  smtp:
    image: rnwood/smtp4dev
    container_name: smtp4dev2
    ports:
      - "6025:25"
      - "5001:80"
    restart: unless-stopped
